import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";

function makeJwtSecret() {
  return randomBytes(32).toString("hex");
}

function parseExistingKeys(filePath) {
  if (!existsSync(filePath)) {
    return new Set();
  }

  const content = readFileSync(filePath, "utf8");
  const keys = new Set();

  for (const line of content.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=/);
    if (match) {
      keys.add(match[1]);
    }
  }

  return keys;
}

export function parseEnvValues(filePath) {
  if (!existsSync(filePath)) {
    return {};
  }

  const content = readFileSync(filePath, "utf8");
  const values = {};

  for (const line of content.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!match) {
      continue;
    }

    values[match[1]] = match[2];
  }

  return values;
}

function renderEntry(entry) {
  const lines = [];

  if (entry.comment) {
    for (const line of entry.comment) {
      lines.push(`# ${line}`);
    }
  }

  lines.push(`${entry.key}=${entry.value}`);
  return lines.join("\n");
}

function renderCommentedExample(entry) {
  const lines = [];

  if (entry.comment) {
    for (const line of entry.comment) {
      lines.push(`# ${line}`);
    }
  }

  lines.push(`# ${entry.key}=${entry.value}`);
  return lines.join("\n");
}

function renderValueEntry(entry, value) {
  const lines = [];

  if (entry.comment) {
    for (const line of entry.comment) {
      lines.push(`# ${line}`);
    }
  }

  lines.push(`${entry.key}=${value}`);
  return lines.join("\n");
}

function renderEnvFile(schema) {
  const parts = [
    `# Auto-generated by npm run setup:env`,
    `# Target: ${schema.targetLabel}`,
    `# Active vars below are required or intentionally customized for local development.`,
  ];

  for (const section of schema.sections) {
    const activeEntries = section.entries.filter((entry) => !entry.skipByDefault);
    const skippedEntries = section.entries.filter((entry) => entry.skipByDefault);

    if (activeEntries.length === 0 && skippedEntries.length === 0) {
      continue;
    }

    parts.push("");
    parts.push(`# ${section.title}`);

    if (activeEntries.length > 0) {
      for (const entry of activeEntries) {
        parts.push(renderEntry(entry));
        parts.push("");
      }
      parts.pop();
    }

    if (skippedEntries.length > 0) {
      parts.push("");
      parts.push(`# Optional defaults skipped for now.`);
      parts.push(`# Uncomment only when you need to override app fallback behavior.`);

      for (const entry of skippedEntries) {
        parts.push(renderCommentedExample(entry));
        parts.push("");
      }
      parts.pop();
    }
  }

  return `${parts.join("\n").trim()}\n`;
}

function appendMissingEntries(schema, missingEntries) {
  const chunks = [
    "",
    "# Added by npm run setup:env",
  ];

  for (const entry of missingEntries) {
    chunks.push(renderEntry(entry));
    chunks.push("");
  }

  appendFileSync(schema.targetPath, `${chunks.join("\n").trimEnd()}\n`);
}

export function createEnvSchemas(rootDir) {
  return [
    {
      name: "frontend",
      targetLabel: "frontend/.env.local",
      targetPath: path.join(rootDir, "frontend", ".env.local"),
      sections: [
        {
          title: "Frontend routing",
          entries: [
            {
              key: "NEXT_PUBLIC_API_URL",
              value: "http://localhost:3100/api",
              prompt: "Frontend API URL",
              comment: [
                "Backend API base URL.",
                "Frontend requests break without this in normal local setup.",
              ],
            },
            {
              key: "NEXT_PUBLIC_APP_NAME",
              value: "CodeArea",
              prompt: "App name",
              skipByDefault: true,
              comment: ["Runtime already defaults to CodeArea."],
            },
            {
              key: "NEXT_PUBLIC_SITE_URL",
              value: "http://localhost:3000",
              prompt: "Frontend site URL",
              skipByDefault: true,
              comment: ["Runtime already defaults to local frontend URL."],
            },
          ],
        },
        {
          title: "Frontend optional integrations",
          entries: [
            {
              key: "NEXT_PUBLIC_AI_URL",
              value: "http://127.0.0.1:8000",
              prompt: "AI service URL",
              skipByDefault: true,
              comment: [
                "Optional separate AI service URL.",
                "If omitted, AI requests fall back to NEXT_PUBLIC_API_URL.",
              ],
            },
            {
              key: "NEXT_PUBLIC_QUESTION_HINT_PATH",
              value: "api/hint",
              prompt: "AI hint path",
              skipByDefault: true,
              comment: ["Optional custom hint endpoint path."],
            },
            {
              key: "NEXT_PUBLIC_QUESTION_COMPARE_PATH",
              value: "api/compare",
              prompt: "AI compare path",
              skipByDefault: true,
              comment: ["Optional custom code-compare endpoint path."],
            },
            {
              key: "NEXT_PUBLIC_UPLOAD_BASE_URL",
              value: "http://localhost:5000/assets",
              prompt: "Upload asset base URL",
              skipByDefault: true,
              comment: ["Optional asset host override."],
            },
          ],
        },
      ],
    },
    {
      name: "backend",
      targetLabel: "backend/.env",
      targetPath: path.join(rootDir, "backend", ".env"),
      sections: [
        {
          title: "Supabase required",
          entries: [
            {
              key: "SUPABASE_URL",
              value: "https://your-project.supabase.co",
              prompt: "Supabase URL",
              comment: ["Required. Backend exits if this is missing."],
            },
            {
              key: "SUPABASE_PUBLISHABLE_KEY",
              value: "sb_publishable_your-publishable-key",
              prompt: "Supabase publishable key",
              comment: ["Required. Used for standard Supabase client access."],
            },
            {
              key: "SUPABASE_SECRET_KEY",
              value: "sb_secret_your-secret-key",
              prompt: "Supabase secret key",
              comment: [
                "Required. Backend-only key for admin DB access and RLS bypass.",
                "Never expose this value in frontend env.",
              ],
            },
            {
              key: "SUPABASE_STORAGE_QUESTIONS_BUCKET",
              value: "question-pdfs",
              prompt: "Supabase question bucket",
              comment: ["Required by question upload routes."],
            },
            {
              key: "SUPABASE_STORAGE_PROFILES_BUCKET",
              value: "user-profile-img",
              prompt: "Supabase profile images bucket",
              comment: ["Required by profile image upload routes."],
            },
          ],
        },
        {
          title: "Backend auth and server",
          entries: [
            {
              key: "JWT_SECRET",
              value: makeJwtSecret(),
              prompt: "JWT secret",
              generateDefault: true,
              comment: [
                "Required. Random secret generated for every setup.",
                "Replace if you need stable shared tokens across machines.",
              ],
            },
            {
              key: "PORT",
              value: "3100",
              prompt: "Backend port",
              comment: ["Local backend port. Matches frontend default API URL."],
            },
            {
              key: "JWT_EXPIRES_IN",
              value: "7d",
              prompt: "JWT expires in",
              skipByDefault: true,
              comment: ["Runtime already defaults to 7d."],
            },
            {
              key: "NODE_ENV",
              value: "development",
              prompt: "Node environment",
              skipByDefault: true,
              comment: ["Runtime already defaults to development."],
            },
          ],
        },
      ],
    },
  ];
}

export function ensureEnvSchemas(rootDir) {
  const schemas = createEnvSchemas(rootDir);

  for (const schema of schemas) {
    const allEntries = schema.sections.flatMap((section) => section.entries);

    if (!existsSync(schema.targetPath)) {
      writeFileSync(schema.targetPath, renderEnvFile(schema), "utf8");
      console.log(`created ${path.relative(rootDir, schema.targetPath)}`);
      continue;
    }

    const existingKeys = parseExistingKeys(schema.targetPath);
    const missingEntries = allEntries.filter(
      (entry) => !entry.skipByDefault && !existingKeys.has(entry.key)
    );

    if (missingEntries.length === 0) {
      console.log(`skip ${path.relative(rootDir, schema.targetPath)}: already has required keys`);
      continue;
    }

    appendMissingEntries(schema, missingEntries);
    console.log(
      `updated ${path.relative(rootDir, schema.targetPath)} with missing keys: ${missingEntries
        .map((entry) => entry.key)
        .join(", ")}`
    );
  }
}

export function writeEnvFile(schema, selectedValues = {}, existingValues = {}) {
  const parts = [
    `# Auto-generated by npm run setup:env`,
    `# Target: ${schema.targetLabel}`,
    `# Active vars below are required or intentionally customized for local development.`,
  ];

  for (const section of schema.sections) {
    const activeBlocks = [];
    const skippedBlocks = [];

    for (const entry of section.entries) {
      const value = selectedValues[entry.key] ?? existingValues[entry.key];

      if (value && String(value).trim() !== "") {
        activeBlocks.push(renderValueEntry(entry, value));
        continue;
      }

      if (entry.skipByDefault) {
        skippedBlocks.push(renderCommentedExample(entry));
      }
    }

    if (activeBlocks.length === 0 && skippedBlocks.length === 0) {
      continue;
    }

    parts.push("");
    parts.push(`# ${section.title}`);

    for (const block of activeBlocks) {
      parts.push(block);
      parts.push("");
    }
    if (activeBlocks.length > 0) {
      parts.pop();
    }

    if (skippedBlocks.length > 0) {
      parts.push("");
      parts.push(`# Optional defaults skipped for now.`);
      parts.push(`# Uncomment only when you need to override app fallback behavior.`);

      for (const block of skippedBlocks) {
        parts.push(block);
        parts.push("");
      }
      parts.pop();
    }
  }

  writeFileSync(schema.targetPath, `${parts.join("\n").trim()}\n`, "utf8");
}
