import "@/scripts/load-env";
import { eq } from "drizzle-orm";
import { closeDb, getDb } from "@/server/db/client";
import { problems, roles, users } from "@/server/db/schema";
import { createProblem, publishProblem } from "@/server/problems/module";
import type { AuthUser } from "@/server/auth/module";

const CATEGORY_ALGORITHMS = 1;
const CATEGORY_DATA_STRUCTURES = 2;

type SeedProblem = {
  slug: string;
  title: string;
  categoryId: number;
  difficulty: 1 | 2 | 3;
  description: string;
  constraints: string;
  expectedComplexity: string;
  timeLimitMs: number;
  memoryLimitKb: number;
  points: number;
  tags: string[];
  testCases: { input: string; output: string; isPublic: boolean }[];
};

const problemsToSeed: SeedProblem[] = [
  {
    slug: "sum-two-numbers",
    title: "ผลรวมของตัวเลขสองจำนวน",
    categoryId: CATEGORY_ALGORITHMS,
    difficulty: 1,
    description: [
      "## โจทย์",
      "",
      "จงเขียนโปรแกรมรับจำนวนเต็มสองจำนวน แล้วพิมพ์ผลรวมของทั้งสองจำนวนนั้น",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "หนึ่งบรรทัด ประกอบด้วยจำนวนเต็ม A และ B คั่นด้วยช่องว่าง",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ค่า A + B",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "3 5",
      "```",
      "Output:",
      "```",
      "8",
      "```",
    ].join("\n"),
    constraints: "-1000 ≤ A, B ≤ 1000",
    expectedComplexity: "O(1)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 100,
    tags: ["math", "io"],
    testCases: [
      { input: "3 5", output: "8", isPublic: true },
      { input: "-10 20", output: "10", isPublic: false },
      { input: "0 0", output: "0", isPublic: false },
    ],
  },
  {
    slug: "reverse-string",
    title: "กลับด้านข้อความ",
    categoryId: CATEGORY_DATA_STRUCTURES,
    difficulty: 1,
    description: [
      "## โจทย์",
      "",
      "จงเขียนโปรแกรมรับข้อความหนึ่งบรรทัด แล้วพิมพ์ข้อความนั้นแบบกลับด้าน",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "หนึ่งบรรทัด เป็นข้อความ S",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ข้อความ S ที่กลับด้านแล้ว",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "hello",
      "```",
      "Output:",
      "```",
      "olleh",
      "```",
    ].join("\n"),
    constraints: "1 ≤ ความยาวของ S ≤ 1000 ตัวอักษร และไม่มีช่องว่าง",
    expectedComplexity: "O(N)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 100,
    tags: ["string"],
    testCases: [
      { input: "hello", output: "olleh", isPublic: true },
      { input: "CodeArea", output: "aeRAedoC", isPublic: false },
      { input: "a", output: "a", isPublic: false },
    ],
  },
  {
    slug: "max-in-array",
    title: "ค่ามากที่สุดในอาเรย์",
    categoryId: CATEGORY_DATA_STRUCTURES,
    difficulty: 1,
    description: [
      "## โจทย์",
      "",
      "จงเขียนโปรแกรมรับจำนวนเต็ม N ตัว แล้วพิมพ์ค่าที่มากที่สุด",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "บรรทัดที่ 1: จำนวนเต็ม N",
      "",
      "บรรทัดที่ 2: จำนวนเต็ม N ตัว คั่นด้วยช่องว่าง",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ค่ามากที่สุดในอาเรย์",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "5",
      "3 7 2 9 4",
      "```",
      "Output:",
      "```",
      "9",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N ≤ 1000, -10^6 ≤ ค่าแต่ละตัว ≤ 10^6",
    expectedComplexity: "O(N)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 100,
    tags: ["array"],
    testCases: [
      { input: "5\n3 7 2 9 4", output: "9", isPublic: true },
      { input: "1\n-5", output: "-5", isPublic: false },
      { input: "4\n10 10 10 10", output: "10", isPublic: false },
    ],
  },
  {
    slug: "count-pairs-sum",
    title: "นับคู่ที่ผลรวมเท่ากับเป้าหมาย",
    categoryId: CATEGORY_DATA_STRUCTURES,
    difficulty: 2,
    description: [
      "## โจทย์",
      "",
      "กำหนดอาเรย์ของจำนวนเต็ม N ตัว และค่าเป้าหมาย T จงนับจำนวนคู่ดัชนี (i, j)",
      "ที่ i < j และ a[i] + a[j] = T",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "บรรทัดที่ 1: จำนวนเต็ม N และ T คั่นด้วยช่องว่าง",
      "",
      "บรรทัดที่ 2: จำนวนเต็ม N ตัว คั่นด้วยช่องว่าง",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์จำนวนคู่ดัชนีที่ผลรวมเท่ากับ T",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "5 6",
      "1 5 3 3 2",
      "```",
      "Output:",
      "```",
      "2",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N ≤ 1000, -10^4 ≤ ค่าแต่ละตัว, T ≤ 10^4",
    expectedComplexity: "O(N)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 200,
    tags: ["array", "hashmap"],
    testCases: [
      { input: "5 6\n1 5 3 3 2", output: "2", isPublic: true },
      { input: "4 10\n5 5 5 5", output: "6", isPublic: false },
      { input: "3 100\n1 2 3", output: "0", isPublic: false },
    ],
  },
  {
    slug: "valid-parentheses",
    title: "ตรวจวงเล็บสมดุล",
    categoryId: CATEGORY_DATA_STRUCTURES,
    difficulty: 2,
    description: [
      "## โจทย์",
      "",
      "กำหนดสตริงที่ประกอบด้วยวงเล็บ `()[]{}` จงตรวจสอบว่าวงเล็บทั้งหมดปิดสมดุลถูกต้องหรือไม่",
      "(เปิด-ปิดครบคู่ และเรียงลำดับถูกต้อง)",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "หนึ่งบรรทัด เป็นสตริงวงเล็บ",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ `YES` ถ้าสมดุล มิฉะนั้นพิมพ์ `NO`",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "()[]{}",
      "```",
      "Output:",
      "```",
      "YES",
      "```",
    ].join("\n"),
    constraints: "1 ≤ ความยาวของสตริง ≤ 1000 และมีเฉพาะอักขระ ()[]{}",
    expectedComplexity: "O(N)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 200,
    tags: ["stack"],
    testCases: [
      { input: "()[]{}", output: "YES", isPublic: true },
      { input: "(]", output: "NO", isPublic: false },
      { input: "{[()]}", output: "YES", isPublic: false },
    ],
  },
  {
    slug: "binary-search",
    title: "การค้นหาแบบทวิภาค",
    categoryId: CATEGORY_ALGORITHMS,
    difficulty: 2,
    description: [
      "## โจทย์",
      "",
      "กำหนดอาเรย์จำนวนเต็ม N ตัว เรียงเพิ่มขึ้นเคร่งครัด (ไม่มีค่าซ้ำ) และคำถาม Q ข้อ",
      "แต่ละคำถามให้ค่า V จงหาตำแหน่ง (เริ่มนับที่ 0) ของ V ในอาเรย์ ถ้าไม่พบให้ตอบ -1",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "บรรทัดที่ 1: จำนวนเต็ม N",
      "",
      "บรรทัดที่ 2: จำนวนเต็ม N ตัว เรียงเพิ่มขึ้นเคร่งครัด",
      "",
      "บรรทัดที่ 3: จำนวนเต็ม Q",
      "",
      "อีก Q บรรทัดถัดไป: แต่ละบรรทัดมีค่า V หนึ่งค่า",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ผลลัพธ์ของแต่ละคำถาม บรรทัดละหนึ่งค่า",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "5",
      "1 3 5 7 9",
      "3",
      "5",
      "2",
      "9",
      "```",
      "Output:",
      "```",
      "2",
      "-1",
      "4",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N, Q ≤ 10^5, -10^9 ≤ ค่าแต่ละตัว ≤ 10^9",
    expectedComplexity: "O(log N)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 200,
    tags: ["binary-search"],
    testCases: [
      {
        input: "5\n1 3 5 7 9\n3\n5\n2\n9",
        output: "2\n-1\n4",
        isPublic: true,
      },
      { input: "1\n10\n2\n10\n5", output: "0\n-1", isPublic: false },
      {
        input: "6\n-5 -3 0 2 8 100\n1\n100",
        output: "5",
        isPublic: false,
      },
    ],
  },
  {
    slug: "merge-sorted-arrays",
    title: "รวมอาเรย์ที่เรียงแล้วสองชุด",
    categoryId: CATEGORY_DATA_STRUCTURES,
    difficulty: 2,
    description: [
      "## โจทย์",
      "",
      "กำหนดอาเรย์จำนวนเต็มสองชุดที่เรียงไม่ลดลงแล้ว จงรวมเป็นอาเรย์เดียวที่เรียงไม่ลดลง",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "บรรทัดที่ 1: จำนวนเต็ม N และ M คั่นด้วยช่องว่าง",
      "",
      "บรรทัดที่ 2: จำนวนเต็ม N ตัว (อาเรย์แรก เรียงไม่ลดลง)",
      "",
      "บรรทัดที่ 3: จำนวนเต็ม M ตัว (อาเรย์ที่สอง เรียงไม่ลดลง)",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์อาเรย์ที่รวมแล้วและเรียงไม่ลดลง คั่นด้วยช่องว่าง ในบรรทัดเดียว",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "3 2",
      "1 3 5",
      "2 4",
      "```",
      "Output:",
      "```",
      "1 2 3 4 5",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N, M ≤ 1000, -10^6 ≤ ค่าแต่ละตัว ≤ 10^6",
    expectedComplexity: "O(N)",
    timeLimitMs: 1000,
    memoryLimitKb: 65536,
    points: 200,
    tags: ["array", "sorting"],
    testCases: [
      { input: "3 2\n1 3 5\n2 4", output: "1 2 3 4 5", isPublic: true },
      { input: "4 1\n1 1 2 9\n1", output: "1 1 1 2 9", isPublic: false },
      {
        input: "2 3\n-5 10\n-8 0 20",
        output: "-8 -5 0 10 20",
        isPublic: false,
      },
    ],
  },
  {
    slug: "longest-increasing-subsequence",
    title: "ลำดับย่อยเพิ่มขึ้นยาวที่สุด",
    categoryId: CATEGORY_ALGORITHMS,
    difficulty: 3,
    description: [
      "## โจทย์",
      "",
      "กำหนดอาเรย์จำนวนเต็ม N ตัว จงหาความยาวของลำดับย่อยที่เพิ่มขึ้นเคร่งครัดที่ยาวที่สุด",
      "(Longest Strictly Increasing Subsequence)",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "บรรทัดที่ 1: จำนวนเต็ม N",
      "",
      "บรรทัดที่ 2: จำนวนเต็ม N ตัว คั่นด้วยช่องว่าง",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ความยาวของลำดับย่อยที่เพิ่มขึ้นเคร่งครัดที่ยาวที่สุด (พิมพ์เฉพาะความยาว ไม่ต้องพิมพ์ลำดับ)",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "8",
      "10 9 2 5 3 7 101 18",
      "```",
      "Output:",
      "```",
      "4",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N ≤ 2000, -10^9 ≤ ค่าแต่ละตัว ≤ 10^9",
    expectedComplexity: "O(N log N)",
    timeLimitMs: 2000,
    memoryLimitKb: 65536,
    points: 300,
    tags: ["dp"],
    testCases: [
      {
        input: "8\n10 9 2 5 3 7 101 18",
        output: "4",
        isPublic: true,
      },
      { input: "6\n7 7 7 7 7 7", output: "1", isPublic: false },
      { input: "5\n1 2 3 4 5", output: "5", isPublic: false },
    ],
  },
  {
    slug: "dijkstra-shortest-path",
    title: "เส้นทางสั้นที่สุดแบบ Dijkstra",
    categoryId: CATEGORY_ALGORITHMS,
    difficulty: 3,
    description: [
      "## โจทย์",
      "",
      "กำหนดกราฟไม่มีทิศทาง (undirected) ที่มี N โหนด (หมายเลข 0 ถึง N-1) และ M เส้นเชื่อม",
      "แต่ละเส้นเชื่อมมีน้ำหนักเป็นจำนวนเต็มไม่ติดลบ จงหาระยะทางสั้นที่สุดจากโหนดต้นทาง S",
      "ไปยังโหนดปลายทาง T ถ้าไปไม่ถึงให้ตอบ -1",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "บรรทัดที่ 1: จำนวนเต็ม N และ M คั่นด้วยช่องว่าง",
      "",
      "อีก M บรรทัดถัดไป: แต่ละบรรทัดมี u, v, w หมายถึงเส้นเชื่อมระหว่างโหนด u และ v น้ำหนัก w",
      "",
      "บรรทัดสุดท้าย: จำนวนเต็ม S และ T (ต้นทางและปลายทาง) คั่นด้วยช่องว่าง",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์ระยะทางสั้นที่สุดจาก S ไป T หรือ -1 ถ้าไปไม่ถึง",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "5 6",
      "0 1 2",
      "0 2 4",
      "1 2 1",
      "1 3 7",
      "2 4 3",
      "3 4 1",
      "0 4",
      "```",
      "Output:",
      "```",
      "6",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N ≤ 100, 0 ≤ M ≤ 1000, 0 ≤ น้ำหนักแต่ละเส้น ≤ 1000",
    expectedComplexity: "O(N^2)",
    timeLimitMs: 2000,
    memoryLimitKb: 65536,
    points: 300,
    tags: ["graph", "shortest-path"],
    testCases: [
      {
        input: "5 6\n0 1 2\n0 2 4\n1 2 1\n1 3 7\n2 4 3\n3 4 1\n0 4",
        output: "6",
        isPublic: true,
      },
      { input: "3 1\n0 1 5\n0 2", output: "-1", isPublic: false },
      {
        input: "4 4\n0 1 1\n1 2 1\n2 3 1\n0 3 10\n0 3",
        output: "3",
        isPublic: false,
      },
    ],
  },
  {
    slug: "n-queens-count",
    title: "นับคำตอบ N-Queens",
    categoryId: CATEGORY_ALGORITHMS,
    difficulty: 3,
    description: [
      "## โจทย์",
      "",
      "กำหนดจำนวนเต็ม N จงนับจำนวนวิธีการวางตัวเบี้ยราชินี (Queen) จำนวน N ตัว",
      "บนกระดานหมากรุกขนาด N x N โดยไม่ให้ราชินีสองตัวใดโจมตีกันได้",
      "(ไม่อยู่แถวเดียวกัน หลักเดียวกัน หรือเส้นทแยงมุมเดียวกัน)",
      "",
      "## รูปแบบข้อมูลนำเข้า (Input)",
      "",
      "หนึ่งบรรทัด เป็นจำนวนเต็ม N",
      "",
      "## รูปแบบข้อมูลส่งออก (Output)",
      "",
      "พิมพ์จำนวนวิธีการวางที่แตกต่างกันทั้งหมด",
      "",
      "## ตัวอย่าง",
      "",
      "Input:",
      "```",
      "4",
      "```",
      "Output:",
      "```",
      "2",
      "```",
    ].join("\n"),
    constraints: "1 ≤ N ≤ 8",
    expectedComplexity: "O(N!)",
    timeLimitMs: 2000,
    memoryLimitKb: 65536,
    points: 300,
    tags: ["backtracking"],
    testCases: [
      { input: "4", output: "2", isPublic: true },
      { input: "1", output: "1", isPublic: false },
      { input: "8", output: "92", isPublic: false },
    ],
  },
];

async function main() {
  const db = getDb();

  const [adminRole] = await db.select().from(roles).where(eq(roles.name, "admin")).limit(1);
  if (!adminRole) throw new Error("ไม่พบ role 'admin' — รัน `npm run db:seed` ก่อน");
  const [adminRow] = await db.select().from(users).where(eq(users.roleId, adminRole.id)).limit(1);
  if (!adminRow) throw new Error("ไม่พบผู้ใช้ที่มี role admin ในระบบ");

  const actor: AuthUser = {
    id: adminRow.id,
    authUserId: adminRow.authUserId,
    email: adminRow.email,
    emailVerified: true,
    displayName: adminRow.displayName,
    role: "admin",
    roleId: adminRow.roleId,
  };

  for (const item of problemsToSeed) {
    const [existing] = await db.select({ id: problems.id }).from(problems).where(eq(problems.slug, item.slug)).limit(1);
    if (existing) {
      console.log(`[skip] ${item.slug} มีอยู่แล้ว`);
      continue;
    }

    await createProblem(
      {
        slug: item.slug,
        title: item.title,
        category_id: item.categoryId,
        difficulty: item.difficulty,
        description: item.description,
        constraints: item.constraints,
        expected_complexity: item.expectedComplexity,
        time_limit: item.timeLimitMs,
        memory_limit: item.memoryLimitKb,
        points: item.points,
        tag: item.tags,
        test_cases: item.testCases.map((tc, index) => ({
          input_data: tc.input,
          output_data: tc.output,
          case_order: index + 1,
          is_simple: tc.isPublic,
          status: true,
        })),
      },
      actor,
    );
    await publishProblem(item.slug, actor);
    console.log(`[created] ${item.slug} (${item.title})`);
  }

  await closeDb();
}

main().catch(async (error) => {
  console.error(error);
  await closeDb();
  process.exitCode = 1;
});
